<?xml version="1.0" encoding="UTF-8" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
            http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
      <groupId>org.rpgwizard</groupId>
      <artifactId>rpgwizard</artifactId>
      <version>1.7.0</version>
    </parent>

    <artifactId>editor</artifactId>
    <packaging>pom</packaging>
    <inceptionYear>2017</inceptionYear>
    <name>RPGWizard Editor</name>

    <developers>
        <developer>
            <id>swordmaster2k</id>
            <name>Joshua Michael Daly</name>
            <timezone>Europe/Dublin</timezone>
        </developer>
        <developer>
            <id>chutchinson</id>
            <name>Chris Hutchinson</name>
            <timezone>America/Detroit</timezone>
        </developer>
    </developers>

    <repositories>
        <repository>
            <id>remote</id>
            <name>GitHub</name>
            <url>https://github.com/swordmaster2k/rpgwizard</url>
        </repository>
    </repositories>

    <modules>
        <module>editor-ui</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>${json.version}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>core</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Logging -->
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>${commons-io.version}</version>
        </dependency>

        <!-- Automated Swing Testing -->
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-swing-junit</artifactId>
            <version>${assertj.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.version}</version>
                <configuration>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
